// This is just static data so I do not use up my free monthly requests

export const jobs = [
  {
    id: "1474893982",
    date_posted: "2025-03-15T01:48:58",
    date_created: "2025-03-14T20:52:51.886233",
    title: "Client Field Service Engineer I",
    organization: "R3 LLC",
    organization_url: null,
    date_validthrough: null,
    locations_raw: [
      {
        "@type": "Place",
        address: {
          "@type": "PostalAddress",
          addressLocality: "Tysons corner",
          addressRegion: "VA",
          addressCountry: "US",
        },
      },
    ],
    locations_alt_raw: null,
    location_type: null,
    location_requirements_raw: null,
    salary_raw: {
      "@type": "MonetaryAmount",
      currency: "USD",
      value: {
        "@type": "QuantitativeValue",
        minValue: 65000,
        maxValue: 85000,
        unitText: "YEAR",
      },
    },
    employment_type: null,
    url: "https://recruiting.paylocity.com/Recruiting/Jobs/Details/3124111",
    source_type: "ats",
    source: "paylocity",
    source_domain: "recruiting.paylocity.com",
    organization_logo:
      "https://recruiting.paylocity.com/recruiting/jobs/GetLogoFile?moduleId=19762",
    cities_derived: null,
    regions_derived: ["Virginia"],
    countries_derived: ["United States"],
    locations_derived: ["Virginia, United States"],
    timezones_derived: ["America/New_York"],
    lats_derived: [37.5295],
    lngs_derived: [-77.4756],
    remote_derived: false,
  },
  {
    id: "1474876789",
    date_posted: "2025-03-15T01:43:46",
    date_created: "2025-03-14T20:43:58.11231",
    title: "Manufacturing Engineer",
    organization: "Pitco Frialator LLC",
    organization_url: null,
    date_validthrough: null,
    locations_raw: [
      {
        "@type": "Place",
        address: {
          "@type": "PostalAddress",
          streetAddress: "553 Route 3a",
          addressLocality: "Bow",
          addressRegion: "NH",
          postalCode: "03304",
          addressCountry: "US",
        },
      },
    ],
    locations_alt_raw: null,
    location_type: null,
    location_requirements_raw: null,
    salary_raw: null,
    employment_type: null,
    url: "https://recruiting.paylocity.com/Recruiting/Jobs/Details/1445578",
    source_type: "ats",
    source: "paylocity",
    source_domain: "recruiting.paylocity.com",
    organization_logo:
      "https://recruiting.paylocity.com/recruiting/jobs/GetLogoFile?moduleId=23759",
    cities_derived: ["Bow"],
    regions_derived: ["New Hampshire"],
    countries_derived: ["United States"],
    locations_derived: ["Bow, New Hampshire, United States"],
    timezones_derived: ["America/New_York"],
    lats_derived: [43.1308],
    lngs_derived: [-71.5307],
    remote_derived: false,
  },
  {
    id: "1474895444",
    date_posted: "2025-03-15T01:32:34",
    date_created: "2025-03-14T20:55:03.068677",
    title: "Service Desk Engineer",
    organization: "LMT Technology Solutions",
    organization_url: null,
    date_validthrough: null,
    locations_raw: [
      {
        "@type": "Place",
        address: {
          "@type": "PostalAddress",
          streetAddress: "4 Commercial St",
          addressLocality: "Rochester",
          addressRegion: "NY",
          postalCode: "14614-1000",
          addressCountry: "US",
        },
      },
    ],
    locations_alt_raw: null,
    location_type: null,
    location_requirements_raw: null,
    salary_raw: {
      "@type": "MonetaryAmount",
      currency: "USD",
      value: {
        "@type": "QuantitativeValue",
        minValue: 55000,
        maxValue: 65000,
        unitText: "YEAR",
      },
    },
    employment_type: null,
    url: "https://recruiting.paylocity.com/Recruiting/Jobs/Details/3124408",
    source_type: "ats",
    source: "paylocity",
    source_domain: "recruiting.paylocity.com",
    organization_logo:
      "https://recruiting.paylocity.com/recruiting/jobs/GetLogoFile?moduleId=25662",
    cities_derived: ["Rochester"],
    regions_derived: ["New York"],
    countries_derived: ["United States"],
    locations_derived: ["Rochester, New York, United States"],
    timezones_derived: ["America/New_York"],
    lats_derived: [43.168],
    lngs_derived: [-77.6162],
    remote_derived: false,
  },
  {
    id: "1474895436",
    date_posted: "2025-03-15T01:32:32",
    date_created: "2025-03-14T20:54:57.034236",
    title: "Manufacturing Supervisor",
    organization: "Wasco Switches & Sensors",
    organization_url: null,
    date_validthrough: null,
    locations_raw: [
      {
        "@type": "Place",
        address: {
          "@type": "PostalAddress",
          streetAddress: "2245 A Street",
          addressLocality: "Santa Maria",
          addressRegion: "CA",
          postalCode: "93455",
          addressCountry: "US",
        },
      },
    ],
    locations_alt_raw: null,
    location_type: null,
    location_requirements_raw: null,
    salary_raw: {
      "@type": "MonetaryAmount",
      currency: "USD",
      value: { "@type": "QuantitativeValue", unitText: "HOUR", value: 24 },
    },
    employment_type: null,
    url: "https://recruiting.paylocity.com/Recruiting/Jobs/Details/3124524",
    source_type: "ats",
    source: "paylocity",
    source_domain: "recruiting.paylocity.com",
    organization_logo:
      "https://recruiting.paylocity.com/recruiting/jobs/GetLogoFile?moduleId=22818",
    cities_derived: ["Santa Maria"],
    regions_derived: ["California"],
    countries_derived: ["United States"],
    locations_derived: ["Santa Maria, California, United States"],
    timezones_derived: ["America/Los_Angeles"],
    lats_derived: [34.9333],
    lngs_derived: [-120.4431],
    remote_derived: false,
  },
  {
    id: "1474896591",
    date_posted: "2025-03-15T01:31:25",
    date_created: "2025-03-14T20:58:11.721747",
    title: "TEMP - BILINGUAL SALES REPRESENTATIVE (Dallas, TX)",
    organization: "Klass Time LTD",
    organization_url: null,
    date_validthrough: null,
    locations_raw: [
      {
        "@type": "Place",
        address: {
          "@type": "PostalAddress",
          streetAddress: "Off Site",
          addressLocality: "Dallas",
          addressRegion: "TX",
          postalCode: "75246",
          addressCountry: "US",
        },
      },
    ],
    locations_alt_raw: null,
    location_type: null,
    location_requirements_raw: null,
    salary_raw: null,
    employment_type: null,
    url: "https://recruiting.paylocity.com/Recruiting/Jobs/Details/3124531",
    source_type: "ats",
    source: "paylocity",
    source_domain: "recruiting.paylocity.com",
    organization_logo:
      "https://recruiting.paylocity.com/recruiting/jobs/GetLogoFile?moduleId=34443",
    cities_derived: ["Dallas"],
    regions_derived: ["Texas"],
    countries_derived: ["United States"],
    locations_derived: ["Dallas, Texas, United States"],
    timezones_derived: ["America/Chicago"],
    lats_derived: [32.7935],
    lngs_derived: [-96.7667],
    remote_derived: false,
  },
  {
    id: "1474880149",
    date_posted: "2025-03-15T01:30:25",
    date_created: "2025-03-14T20:44:35.923334",
    title: "Maintenance Technician",
    organization: "Embassy Suites Chicago Naperville ",
    organization_url: null,
    date_validthrough: null,
    locations_raw: [
      {
        "@type": "Place",
        address: {
          "@type": "PostalAddress",
          streetAddress: "1823 Abriter Ct",
          addressLocality: "Naperville",
          addressRegion: "IL",
          postalCode: "60563",
          addressCountry: "US",
        },
      },
    ],
    locations_alt_raw: null,
    location_type: null,
    location_requirements_raw: null,
    salary_raw: null,
    employment_type: null,
    url: "https://recruiting.paylocity.com/Recruiting/Jobs/Details/3124520",
    source_type: "ats",
    source: "paylocity",
    source_domain: "recruiting.paylocity.com",
    organization_logo: null,
    cities_derived: ["Naperville"],
    regions_derived: ["Illinois"],
    countries_derived: ["United States"],
    locations_derived: ["Naperville, Illinois, United States"],
    timezones_derived: ["America/Chicago"],
    lats_derived: [41.748],
    lngs_derived: [-88.1659],
    remote_derived: false,
  },
  {
    id: "1474896608",
    date_posted: "2025-03-15T01:29:40",
    date_created: "2025-03-14T20:58:30.384345",
    title: "Play & Learning Specialist - Maker Learning",
    organization: "Thinkery",
    organization_url: null,
    date_validthrough: null,
    locations_raw: [
      {
        "@type": "Place",
        address: {
          "@type": "PostalAddress",
          streetAddress: "1830 SIMOND AVE",
          addressLocality: "AUSTIN",
          addressRegion: "TX",
          postalCode: "78723",
          addressCountry: "US",
        },
      },
    ],
    locations_alt_raw: null,
    location_type: null,
    location_requirements_raw: null,
    salary_raw: {
      "@type": "MonetaryAmount",
      currency: "USD",
      value: { "@type": "QuantitativeValue", unitText: "HOUR", value: 19.5 },
    },
    employment_type: null,
    url: "https://recruiting.paylocity.com/Recruiting/Jobs/Details/3124279",
    source_type: "ats",
    source: "paylocity",
    source_domain: "recruiting.paylocity.com",
    organization_logo:
      "https://recruiting.paylocity.com/recruiting/jobs/GetLogoFile?moduleId=34317",
    cities_derived: ["Austin"],
    regions_derived: ["Texas"],
    countries_derived: ["United States"],
    locations_derived: ["Austin, Texas, United States"],
    timezones_derived: ["America/Chicago"],
    lats_derived: [30.3005],
    lngs_derived: [-97.7522],
    remote_derived: false,
  },
  {
    id: "1474876551",
    date_posted: "2025-03-15T01:29:18",
    date_created: "2025-03-14T20:43:56.458629",
    title: "Quality Engineer",
    organization: "Beacon EmbeddedWorks",
    organization_url: null,
    date_validthrough: null,
    locations_raw: [
      {
        "@type": "Place",
        address: {
          "@type": "PostalAddress",
          streetAddress: "6201 Bury Drive",
          addressLocality: "Eden Prairie",
          addressRegion: "MN",
          postalCode: "55346",
          addressCountry: "US",
        },
      },
    ],
    locations_alt_raw: null,
    location_type: null,
    location_requirements_raw: null,
    salary_raw: null,
    employment_type: null,
    url: "https://recruiting.paylocity.com/Recruiting/Jobs/Details/3124491",
    source_type: "ats",
    source: "paylocity",
    source_domain: "recruiting.paylocity.com",
    organization_logo:
      "https://recruiting.paylocity.com/recruiting/jobs/GetLogoFile?moduleId=17768",
    cities_derived: ["Eden Prairie"],
    regions_derived: ["Minnesota"],
    countries_derived: ["United States"],
    locations_derived: ["Eden Prairie, Minnesota, United States"],
    timezones_derived: ["America/Chicago"],
    lats_derived: [44.8488],
    lngs_derived: [-93.4595],
    remote_derived: false,
  },
  {
    id: "1474879346",
    date_posted: "2025-03-15T01:28:15",
    date_created: "2025-03-14T20:44:23.891846",
    title: "Team Member",
    organization: "LALALAND CA 763 AMERICANA WAY LLC",
    organization_url: null,
    date_validthrough: null,
    locations_raw: [
      {
        "@type": "Place",
        address: {
          "@type": "PostalAddress",
          streetAddress: "763 Americana Way, Store #144",
          addressLocality: "Glendale",
          addressRegion: "CA",
          postalCode: "91210",
          addressCountry: "US",
        },
      },
    ],
    locations_alt_raw: null,
    location_type: null,
    location_requirements_raw: null,
    salary_raw: null,
    employment_type: null,
    url: "https://recruiting.paylocity.com/Recruiting/Jobs/Details/3124517",
    source_type: "ats",
    source: "paylocity",
    source_domain: "recruiting.paylocity.com",
    organization_logo:
      "https://recruiting.paylocity.com/recruiting/jobs/GetLogoFile?moduleId=30329",
    cities_derived: ["Glendale"],
    regions_derived: ["California"],
    countries_derived: ["United States"],
    locations_derived: ["Glendale, California, United States"],
    timezones_derived: ["America/Los_Angeles"],
    lats_derived: [34.1819],
    lngs_derived: [-118.2468],
    remote_derived: false,
  },
  {
    id: "1474882564",
    date_posted: "2025-03-15T01:27:53",
    date_created: "2025-03-14T20:45:17.773075",
    title: "CENA",
    organization: "SKLD Plymouth ",
    organization_url: null,
    date_validthrough: null,
    locations_raw: [
      {
        "@type": "Place",
        address: {
          "@type": "PostalAddress",
          streetAddress: "105 N. Haggerty Road",
          addressLocality: "Plymouth",
          addressRegion: "MI",
          postalCode: "48170",
          addressCountry: "US",
        },
      },
    ],
    locations_alt_raw: null,
    location_type: null,
    location_requirements_raw: null,
    salary_raw: null,
    employment_type: null,
    url: "https://recruiting.paylocity.com/Recruiting/Jobs/Details/3124516",
    source_type: "ats",
    source: "paylocity",
    source_domain: "recruiting.paylocity.com",
    organization_logo:
      "https://recruiting.paylocity.com/recruiting/jobs/GetLogoFile?moduleId=16516",
    cities_derived: ["Plymouth"],
    regions_derived: ["Michigan"],
    countries_derived: ["United States"],
    locations_derived: ["Plymouth, Michigan, United States"],
    timezones_derived: ["America/Detroit"],
    lats_derived: [42.3718],
    lngs_derived: [-83.468],
    remote_derived: false,
  },
];
